
# top level setting
line-length = 88
indent-width = 4

# assume Python 3.10
target-version = "py310"

# exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# =============================================================================
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 100

# =============================================================================
[lint]
select = [
    # "ALL", # all existing linter plugins
    "F", # Pyflakes
    "E", # error - pycodestyle
    "W", # warning - pycodestyle
    "B", # flake8-bugbear
    "C90", # mccabe
    "I", # iSort
    "N", # pep8 Naming
    "S", # flake8-bandit
    "PL", # Pylint
]
extend-select = [
    "D", # pydocstyle
]
# https://docs.astral.sh/ruff/rules/
ignore = [
    "PLR1711", # useless-return
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# -----------------------------------------------------------------------------
[lint.per-file-ignores]
"**/tests/**" = [
    "S101", # assert
]
"tests/*" = ["D"]

# -----------------------------------------------------------------------------
[lint.flake8-bandit]
hardcoded-tmp-directory = []

[lint.isort]
case-sensitive = true
force-sort-within-sections = false
from-first = true
# known-first-party = ["src"]
known-local-folder = ["src", "tests"]
no-lines-before = ["future", "standard-library"]
no-sections = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
# default-section = "first-party"
split-on-trailing-comma = true

[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 5

[lint.pycodestyle]
max-line-length = 88
max-doc-length = 88

[lint.pydocstyle]
convention = "google"

[lint.pylint]
max-args = 8
max-bool-expr = 5
max-branches = 12
max-locals = 15
max-nested-blocks = 5

# =============================================================================
