---
services:
  debian:
    container_name: sandbox-debian
    image: sandbox-debian:0.0.1
    build:
      context: $PWD
      dockerfile: Dockerfile
    # ---------------keep container running------------sys----
    tty: true
    command: /bin/bash
    # command: tail -f /dev/null
    # -----------------------------------------------------
    ports:
    - "8080:8080"
    volumes:
    - ./dir_working:/root/volume
    networks:
      sanbox:
        ipv4_address: 20.20.0.12

networks:
  sanbox:
    name: sanbox
    driver: bridge
    ipam:
      config:
      - subnet: 20.20.0.0/26
