%YAML 1.2
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: check-merge-conflict
  - id: detect-private-key
  - id: no-commit-to-branch
    args: [--branch, master]
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - -m=VERTICAL_HANGING_INDENT
    # specify the directory for --from-first is mandatory
    - --from-first=.
    - --only-sections
    # need the trailing comma to avoid the conflict with black's auto-formatting
    - --trailing-comma
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=88
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
  - id: mypy
    args:
    - --no-strict-optional
    - --namespace-packages
    - --explicit-package-bases
#    - --ignore-missing-imports
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint
    args:
    - --disable=E0401 #(import-error), pyenv not detected issue
    - --disable=C0301 #(line-too-long)
    - --disable=R1711 #(useless-return)
    # note that the pattern below is not feasible:
    # "(?:(?P<custom>)|(?P<snake>([^\\W\\dA-Z][^\\WA-Z]{2,}|_[^\\WA-Z]*|__[^\\WA-Z\\d_][^\\WA-Z]+__)))$"
    - --variable-rgx=(?:(?P<custom>(x|y|i|j|[^\W\dA-Z][^\WA-Z]{1,}|_[^\WA-Z]*|__[^\WA-Z\d_][^\WA-Z]+__)))$
    - --include-naming-hint=y
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    language_version: python3.8
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args:
    - -c=dev/bandit.yaml
- repo: https://github.com/tonybaloney/wily
  rev: 1.24.1
  hooks:
  - id: wily
    name: wily
    verbose: true
    language: python
    additional_dependencies: [wily]
    entry: wily diff
    args:
    - --changes-only
    - --no-detail
