version: "3"

services:
  centos:
    container_name: sandbox-centos
    image: lab-centos:0.0.1
    build:
      context: $PWD
      dockerfile: Dockerfile
    tty: true   # keep container running
    ports:
    - "8080:8080"
    volumes:
    - ./vol_working:/root/volume
