
# pdf operations
run-pdf-draft:
	python -m pdf \
		--operation draft

run-pdf-split:
	python -m pdf \
		--operation split \
		--name "pdf/input/sample.pdf"

run-pdf-merge:
	python -m pdf \
		--operation merge \
		--input "pdf/input"

run-pdf-extract:
	python -m pdf \
		--operation extract \
		--name "pdf/input/sample.pdf"

run-pdf-rotate:
	python -m pdf \
		--operation rotate \
		--name "pdf/input/sample.pdf"

run-pdf-watermark:
	python -m pdf \
		--operation watermark \
		--name "pdf/input/sample.pdf"

run-pdf-text:
	python -m pdf \
		--operation text \
		--name "pdf/input/sample.pdf"

run-pdf-crop:
	python -m pdf \
		--operation crop \
		--name "pdf/input/sample.pdf"

run-pdf-encrypt:
	python -m pdf \
		--operation encrypt \
		--name "pdf/input/sample.pdf"

run-pdf-decrypt:
	python -m pdf \
		--operation decrypt \
		--name "pdf/input/encrypted.pdf"
