
run-pdf-draft:
	python -m pdf \
		--operation draft

run-pdf-split:
	python -m pdf \
		--operation split \
		--name "pdf/sample.pdf"

run-pdf-merge:
	python -m pdf \
		--operation merge \
		--input "pdf/input"
