
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://dev.xxx.xxx:6443
  name: dev-k8s
- cluster:
    insecure-skip-tls-verify: true
    server: https://uat.xxx.xxx:6443
  name: uat-k8s
- cluster:
    insecure-skip-tls-verify: true
    server: https://xxx.xxx:6443
  name: prd-k8s
contexts:
- context:
    cluster: dev-k8s
    namespace: dummy-dev
    user: inhouse-dev-sa
  name: dev-k8s
- context:
    cluster: uat-k8s
    namespace: dummy-uat
    user: inhouse-uat-sa
  name: uat-k8s
- context:
    cluster: prd-k8s
    namespace: dummy-prd
    user: inhouse-prd-sa
  name: prd-k8s
current-context: dev-k8s
kind: Config
preferences: {}
users:
- name: inhouse-dev-sa
  user:
    token: xxx
- name: inhouse-uat-sa
  user:
    token: xxx
- name: inhouse-prd-sa
  user:
    token: xxx
